import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { KeyRound, Plus, ShieldCheck, Users } from 'lucide-react'
import AdminLayout from '../AdminLayout'
import { api, ApiError } from '../api'
import { useAuth } from '../auth'
import Toast, { ToastState } from '../Toast'

interface ManagedUser { id: string; email: string; role: 'ADMIN' | 'EDITOR' | 'VIEWER'; is_active: boolean; totp_enabled: boolean; last_login_at?: string }

export default function AccountPage() {
  const auth = useAuth(); const client = useQueryClient(); const [toast, setToast] = useState<ToastState | null>(null)
  const [passwords, setPasswords] = useState({ current_password: '', new_password: '' })
  const [setup, setSetup] = useState<{ secret: string; otpauth_url: string } | null>(null); const [otp, setOtp] = useState('')
  const [newUser, setNewUser] = useState({ email: '', password: '', role: 'VIEWER' })
  const users = useQuery({ queryKey: ['users'], queryFn: () => api<{ items: ManagedUser[] }>('/users'), enabled: auth.user?.role === 'ADMIN' })
  const message = (type: 'success' | 'error', value: string) => setToast({ type, message: value })
  const password = useMutation({ mutationFn: () => api('/auth/password', { method: 'POST', body: JSON.stringify(passwords) }), onSuccess: () => { setPasswords({ current_password: '', new_password: '' }); sessionStorage.removeItem('password-warning'); message('success', 'Parol yangilandi') }, onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  const setup2fa = useMutation({ mutationFn: () => api<{ secret: string; otpauth_url: string }>('/auth/2fa/setup', { method: 'POST' }), onSuccess: setSetup, onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  const enable2fa = useMutation({ mutationFn: () => api('/auth/2fa/enable', { method: 'POST', body: JSON.stringify({ code: otp }) }), onSuccess: async () => { await auth.check(); setSetup(null); setOtp(''); message('success', '2FA yoqildi') }, onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  const disable2fa = useMutation({ mutationFn: () => api('/auth/2fa/disable', { method: 'POST', body: JSON.stringify({ code: otp }) }), onSuccess: async () => { await auth.check(); setOtp(''); message('success', "2FA o'chirildi") }, onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  const createUser = useMutation({ mutationFn: () => api('/users', { method: 'POST', body: JSON.stringify(newUser) }), onSuccess: () => { setNewUser({ email: '', password: '', role: 'VIEWER' }); void client.invalidateQueries({ queryKey: ['users'] }); message('success', 'Foydalanuvchi yaratildi') }, onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  const updateUser = useMutation({ mutationFn: ({ id, changes }: { id: string; changes: object }) => api(`/users/${id}`, { method: 'PATCH', body: JSON.stringify(changes) }), onSuccess: () => void client.invalidateQueries({ queryKey: ['users'] }), onError: (error) => message('error', error instanceof ApiError ? error.message : 'Xato') })
  return <AdminLayout title="Hisob va foydalanuvchilar" subtitle="Parol, 2FA va rollarga asoslangan ruxsatlar">
    <div className="settings-grid">
      <section className="panel settings-card"><div className="settings-title"><span><KeyRound/></span><div><h2>Parolni yangilash</h2><p>Kamida 12 belgili yangi parol</p></div></div><label><span>Joriy parol</span><input type="password" value={passwords.current_password} onChange={(e) => setPasswords({ ...passwords, current_password: e.target.value })}/></label><label><span>Yangi parol</span><input type="password" minLength={12} value={passwords.new_password} onChange={(e) => setPasswords({ ...passwords, new_password: e.target.value })}/></label><button className="btn primary" disabled={password.isPending || passwords.new_password.length < 12} onClick={() => password.mutate()}><KeyRound/> Yangilash</button></section>
      <section className="panel settings-card"><div className="settings-title"><span><ShieldCheck/></span><div><h2>Ikki bosqichli himoya</h2><p>Authenticator ilovasi bilan TOTP</p></div></div><p className="settings-copy">Holat: <strong>{auth.user?.totp_enabled ? 'Yoqilgan' : "O'chirilgan"}</strong></p>{!auth.user?.totp_enabled && !setup && <button className="btn primary" onClick={() => setup2fa.mutate()}>2FA sozlash</button>}{setup && <><label><span>Authenticator ilovasiga kiriting</span><input readOnly value={setup.secret}/><small>Yoki URL: {setup.otpauth_url}</small></label><label><span>6 xonali kod</span><input inputMode="numeric" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}/></label><button className="btn primary" disabled={otp.length !== 6} onClick={() => enable2fa.mutate()}>Tasdiqlash</button></>}{auth.user?.totp_enabled && <><label><span>O'chirish uchun joriy kod</span><input inputMode="numeric" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}/></label><button className="btn danger" disabled={otp.length !== 6} onClick={() => disable2fa.mutate()}>2FA ni o'chirish</button></>}</section>
    </div>
    {auth.user?.role === 'ADMIN' && <section className="panel table-panel operations-section"><div className="panel-heading"><div><Users/><div><h2>Foydalanuvchilar</h2><p>ADMIN, EDITOR va VIEWER rollari</p></div></div></div><div className="inline-create"><input type="email" placeholder="email@example.uz" value={newUser.email} onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}/><input type="password" minLength={12} placeholder="Vaqtinchalik parol" value={newUser.password} onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}/><select value={newUser.role} onChange={(e) => setNewUser({ ...newUser, role: e.target.value })}><option>VIEWER</option><option>EDITOR</option><option>ADMIN</option></select><button className="btn primary" disabled={newUser.password.length < 12} onClick={() => createUser.mutate()}><Plus/> Qo'shish</button></div><div className="responsive-table"><table><thead><tr><th>Email</th><th>Rol</th><th>2FA</th><th>Holat</th></tr></thead><tbody>{users.data?.items.map((item) => <tr key={item.id}><td>{item.email}</td><td><select value={item.role} onChange={(e) => updateUser.mutate({ id: item.id, changes: { role: e.target.value } })}><option>VIEWER</option><option>EDITOR</option><option>ADMIN</option></select></td><td>{item.totp_enabled ? 'Yoqilgan' : '—'}</td><td><button className={`btn compact ${item.is_active ? 'ghost' : 'danger'}`} onClick={() => updateUser.mutate({ id: item.id, changes: { is_active: !item.is_active } })}>{item.is_active ? 'Faol' : 'Nofaol'}</button></td></tr>)}</tbody></table></div></section>}
    <Toast toast={toast} onClose={() => setToast(null)}/>
  </AdminLayout>
}
