import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, AlertTriangle, Database, Download, Play, Upload } from 'lucide-react'
import AdminLayout from '../AdminLayout'
import { api, API_BASE, ApiError } from '../api'
import Toast, { ToastState } from '../Toast'

interface Job { id: string; kind: string; status: string; progress: number; total: number; error?: string; result?: { updated?: string[]; failed?: unknown[] } }
interface Alert { key: string; level: string; title: string; message: string; acknowledged: boolean }

export default function OperationsPage() {
  const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [backupFile, setBackupFile] = useState<File | null>(null); const [confirmation, setConfirmation] = useState(''); const [importType, setImportType] = useState('declarations'); const [preview, setPreview] = useState<any>(null); const [toast, setToast] = useState<ToastState | null>(null)
  const status = useQuery({ queryKey: ['data-status'], queryFn: () => api<any>('/data-status') })
  const alerts = useQuery({ queryKey: ['alerts'], queryFn: () => api<{ items: Alert[] }>('/alerts') })
  const jobs = useQuery({ queryKey: ['jobs'], queryFn: () => api<{ items: Job[] }>('/jobs'), refetchInterval: 3000 })
  const monitoring = useQuery({ queryKey: ['monitoring'], queryFn: () => api<any>('/monitoring?minutes=60') })
  const imports = useQuery({ queryKey: ['imports'], queryFn: () => api<{ items: any[] }>('/imports') })
  const upload = (path: string) => { if (!file) return Promise.reject(new Error('Fayl tanlanmagan')); const body = new FormData(); body.append('import_type', importType); body.append('file', file); return api<any>(path, { method: 'POST', body }) }
  const previewMutation = useMutation({ mutationFn: () => upload('/imports/preview'), onSuccess: setPreview, onError: (e) => setToast({ type: 'error', message: e instanceof ApiError ? e.message : 'CSV tekshirilmadi' }) })
  const commit = useMutation({ mutationFn: () => upload('/imports/commit'), onSuccess: (data) => { setToast({ type: 'success', message: `${data.rows_imported} qator import qilindi` }); setPreview(null); void client.invalidateQueries() }, onError: (e) => setToast({ type: 'error', message: e instanceof ApiError ? e.message : 'Import xatosi' }) })
  const jobAction = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => api(`/jobs/${id}/${action}`, { method: 'POST' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['jobs'] }) })
  const acknowledge = useMutation({ mutationFn: (key: string) => api(`/alerts/${encodeURIComponent(key)}/acknowledge`, { method: 'POST' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['alerts'] }) })
  const restore = useMutation({ mutationFn: () => { if (!backupFile) return Promise.reject(new Error('Backup tanlanmagan')); const body = new FormData(); body.append('confirmation', confirmation); body.append('file', backupFile); return api<any>('/operations/restore', { method: 'POST', body }) }, onSuccess: (data) => { setToast({ type: 'success', message: `${data.posts} post va ${data.corridors} koridor tiklandi` }); setConfirmation(''); setBackupFile(null); void client.invalidateQueries() }, onError: (error) => setToast({ type: 'error', message: error instanceof ApiError ? error.message : 'Backup tiklanmadi' }) })
  return <AdminLayout title="Operatsiyalar markazi" subtitle="Import, fon vazifalari, ogohlantirish va monitoring" actions={<a className="btn ghost compact" href={`${API_BASE}/operations/backup`}><Download/> Backup</a>}>
    <div className="admin-kpis"><article className="admin-kpi blue"><span><Database/></span><div><p>Postlar</p><strong>{status.data?.counts.posts ?? '—'}</strong></div></article><article className="admin-kpi cyan"><span><Database/></span><div><p>Deklaratsiyalar</p><strong>{status.data?.counts.declarations ?? '—'}</strong></div></article><article className="admin-kpi green"><span><Activity/></span><div><p>API p95</p><strong>{monitoring.data?.p95_ms ?? 0} ms</strong></div></article><article className="admin-kpi red"><span><AlertTriangle/></span><div><p>Xatolik foizi</p><strong>{monitoring.data?.error_rate ?? 0}%</strong></div></article></div>
    <div className="dashboard-grid operations-grid"><section className="panel settings-card"><div className="settings-title"><span><Upload/></span><div><h2>Excel / CSV import</h2><p>Avval preview, keyin tasdiqlash</p></div></div><label><span>Ma'lumot turi</span><select value={importType} onChange={(e) => { setImportType(e.target.value); setPreview(null) }}><option value="declarations">Deklaratsiyalar</option><option value="posts">Postlar</option><option value="metrics">Kunlik ko'rsatkichlar</option></select></label><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e) => { setFile(e.target.files?.[0] || null); setPreview(null) }}/><div className="button-row"><button className="btn ghost" disabled={!file || previewMutation.isPending} onClick={() => previewMutation.mutate()}>Tekshirish</button><button className="btn primary" disabled={!preview || !preview.valid || commit.isPending} onClick={() => commit.mutate()}><Upload/> Import qilish</button></div>{preview && <div className="import-preview"><strong>{preview.valid} yaroqli / {preview.rejected} xato</strong>{preview.errors?.slice(0, 5).map((error: any) => <small key={error.row}>{error.row}-qator: {error.message}</small>)}</div>}</section>
      <section className="panel"><div className="panel-heading"><div><AlertTriangle/><div><h2>Ogohlantirishlar</h2><p>Ma'lumot va xavfsizlik nazorati</p></div></div></div>{alerts.data?.items.filter((item) => !item.acknowledged).map((item) => <div className={`status-row ${item.level === 'danger' ? 'error' : ''}`} key={item.key}><span><i/>{item.title}<small>{item.message}</small></span><button className="btn ghost compact" onClick={() => acknowledge.mutate(item.key)}>Ko'rdim</button></div>)}{!alerts.data?.items.some((item) => !item.acknowledged) && <p className="settings-copy">Faol ogohlantirish yo'q.</p>}</section></div>
    <section className="panel settings-card operations-section"><div className="settings-title"><span><Database/></span><div><h2>Backupni tiklash</h2><p>Post, darvoza, koridor va sozlamalarni mavjud bazaga birlashtiradi</p></div></div><label><span>JSON backup fayli</span><input type="file" accept="application/json,.json" onChange={(event) => setBackupFile(event.target.files?.[0] || null)}/></label><label><span>Tasdiqlash uchun RESTORE yozing</span><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="RESTORE"/></label><div className="button-row"><button className="btn danger" disabled={!backupFile || confirmation !== 'RESTORE' || restore.isPending} onClick={() => restore.mutate()}>{restore.isPending ? 'Tiklanmoqda...' : 'Backupni tiklash'}</button></div><p className="settings-copy">Tiklashdan oldin joriy backupni yuklab olish tavsiya etiladi. Amaliyot audit jurnaliga yoziladi.</p></section>
    <section className="panel table-panel operations-section"><div className="panel-heading"><div><Play/><div><h2>Fon vazifalari</h2><p>Route rebuild progress va qayta urinishlar</p></div></div></div><div className="responsive-table"><table><thead><tr><th>Turi</th><th>Holat</th><th>Progress</th><th>Amal</th></tr></thead><tbody>{jobs.data?.items.map((job) => <tr key={job.id}><td>{job.kind}</td><td>{job.status}</td><td><progress max={Math.max(job.total, 1)} value={job.progress}/> {job.progress}/{job.total}</td><td>{['FAILED','COMPLETED_WITH_ERRORS','CANCELLED'].includes(job.status) && <button className="btn ghost compact" onClick={() => jobAction.mutate({ id: job.id, action: 'retry' })}>Qayta</button>}{['PENDING','RUNNING'].includes(job.status) && <button className="btn danger compact" onClick={() => jobAction.mutate({ id: job.id, action: 'cancel' })}>Bekor</button>}</td></tr>)}</tbody></table></div></section>
    <section className="panel table-panel operations-section"><div className="panel-heading"><div><Upload/><div><h2>Import tarixi</h2><p>Oxirgi 100 ta yuklash</p></div></div></div><div className="responsive-table"><table><thead><tr><th>Fayl</th><th>Turi</th><th>Natija</th><th>Sana</th></tr></thead><tbody>{imports.data?.items.map((item) => <tr key={item.id}><td>{item.filename}</td><td>{item.import_type}</td><td>{item.rows_imported} / {item.rows_total}</td><td>{new Date(item.created_at).toLocaleString('uz-UZ')}</td></tr>)}</tbody></table></div></section>
    <Toast toast={toast} onClose={() => setToast(null)}/>
  </AdminLayout>
}
