import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Clipboard, MapPin, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api, ApiError } from '../api'
import LocationPicker from '../features/map/LocationPicker'
import AdminLayout from '../AdminLayout'
import type { CustomsPost } from '../types'
import Toast, { ToastState } from '../Toast'

type PostForm = Omit<CustomsPost, 'id'>
const emptyForm: PostForm = { post_code: '', post_name: '', post_type: 'CHBP', region: '', neighbor_country_code: 'KZ', latitude: undefined, longitude: undefined, location_verified: false, is_active: true }

export default function PostsAdminPage() {
  const [params] = useSearchParams()
  const client = useQueryClient()
  const [search, setSearch] = useState('')
  const [type, setType] = useState('')
  const [editing, setEditing] = useState<CustomsPost | null>(null)
  const [form, setForm] = useState<PostForm>(emptyForm)
  const [open, setOpen] = useState(params.get('new') === '1')
  const [toast, setToast] = useState<ToastState | null>(null)
  const query = useQuery({ queryKey: ['admin-posts', search, type], queryFn: () => { const q = new URLSearchParams({ active_only: 'false', page_size: '500' }); if (search) q.set('search', search); if (type) q.set('post_type', type); return api<{ items: CustomsPost[]; total: number }>(`/posts?${q}`) } })
  const save = useMutation({ mutationFn: () => editing ? api<CustomsPost>(`/posts/${editing.id}`, { method: 'PATCH', body: JSON.stringify(form) }) : api<CustomsPost>('/posts', { method: 'POST', body: JSON.stringify(form) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['admin-posts'] }); setOpen(false); setEditing(null); setForm(emptyForm); setToast({ type: 'success', message: 'Post muvaffaqiyatli saqlandi' }) }, onError: (e) => setToast({ type: 'error', message: e instanceof ApiError ? e.message : 'Saqlashda xato' }) })
  const remove = useMutation({ mutationFn: (id: string) => api(`/posts/${id}`, { method: 'DELETE' }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['admin-posts'] }); setToast({ type: 'success', message: 'Post nofaol qilindi' }) } })
  useEffect(() => { if (!open) setEditing(null) }, [open])
  const startEdit = (post: CustomsPost) => { setEditing(post); setForm({ ...post }); setOpen(true) }
  return <AdminLayout title="Bojxona postlari" subtitle={`${query.data?.total ?? 0} ta post · kodlar string sifatida saqlanadi`} actions={<button className="btn primary" onClick={() => { setForm(emptyForm); setOpen(true) }}><Plus size={17}/> Yangi post</button>}>
    <section className="panel table-panel"><div className="table-toolbar"><div className="input-wrap search-input"><Search/><input placeholder="Kod yoki nom bo'yicha qidirish" value={search} onChange={(e) => setSearch(e.target.value)}/></div><select value={type} onChange={(e) => setType(e.target.value)}><option value="">Barcha turlar</option>{['CHBP','TIF','AERO','RW','PORT'].map((v) => <option key={v}>{v}</option>)}</select></div><div className="responsive-table"><table><thead><tr><th>Post kodi</th><th>Post nomi</th><th>Turi</th><th>Davlat</th><th>Koordinata</th><th>Holati</th><th/></tr></thead><tbody>{query.data?.items.map((post) => <tr key={post.id}><td><button className="copy-code" onClick={() => { void navigator.clipboard.writeText(post.post_code); setToast({ type: 'success', message: 'Post kodi nusxalandi' }) }}><code>{post.post_code}</code><Clipboard/></button></td><td><strong>{post.post_name}</strong></td><td><span className={`type-badge ${post.post_type.toLowerCase()}`}>{post.post_type}</span></td><td>{post.neighbor_country_code || '—'}</td><td>{post.latitude != null ? <span className="location-ok"><MapPin/> {post.latitude.toFixed(4)}, {post.longitude?.toFixed(4)}</span> : <span className="muted">Belgilanmagan</span>}</td><td>{post.is_active ? <span className="status active"><i/>Faol</span> : <span className="status"><i/>Nofaol</span>}</td><td><div className="row-actions"><button onClick={() => startEdit(post)} title="Tahrirlash"><Pencil/></button><button onClick={() => confirm('Post nofaol qilinsinmi?') && remove.mutate(post.id)} title="Nofaol qilish"><Trash2/></button></div></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.items.length && <div className="empty-state"><Search/><strong>Post topilmadi</strong><span>Qidiruv yoki filtrni o'zgartiring.</span></div>}</div></section>
    {open && <div className="modal-backdrop"><div className="admin-modal large" role="dialog" aria-modal="true"><div className="modal-header"><div><p className="eyebrow">{editing ? 'POSTNI TAHRIRLASH' : 'YANGI POST'}</p><h2>{editing?.post_name || "Bojxona postini qo'shish"}</h2></div><button onClick={() => setOpen(false)}><X/></button></div><div className="post-editor"><form onSubmit={(e) => { e.preventDefault(); save.mutate() }}><div className="form-grid"><label><span>Post kodi *</span><input required minLength={3} maxLength={10} disabled={!!editing} value={form.post_code} onChange={(e) => setForm({...form, post_code: e.target.value})}/><small>Masalan: 00101. Yetakchi nol saqlanadi.</small></label><label><span>Post turi *</span><select value={form.post_type} onChange={(e) => setForm({...form, post_type: e.target.value as PostForm['post_type']})}>{['CHBP','TIF','AERO','RW','PORT'].map((v) => <option key={v}>{v}</option>)}</select></label><label className="full"><span>Post nomi *</span><input required value={form.post_name} onChange={(e) => setForm({...form, post_name: e.target.value})}/></label><label><span>Hudud</span><input value={form.region || ''} onChange={(e) => setForm({...form, region: e.target.value})}/></label><label><span>Chegaradosh davlat {form.post_type === 'CHBP' && '*'}</span><select required={form.post_type === 'CHBP'} value={form.neighbor_country_code || ''} onChange={(e) => setForm({...form, neighbor_country_code: e.target.value})}><option value="">Tanlanmagan</option>{['KZ','KG','TJ','TM','AF'].map((v) => <option key={v}>{v}</option>)}</select></label><label><span>Latitude</span><input type="number" step="any" min={-90} max={90} value={form.latitude ?? ''} onChange={(e) => setForm({...form, latitude: e.target.value ? Number(e.target.value) : undefined})}/></label><label><span>Longitude</span><input type="number" step="any" min={-180} max={180} value={form.longitude ?? ''} onChange={(e) => setForm({...form, longitude: e.target.value ? Number(e.target.value) : undefined})}/></label></div><label className="checkbox"><input type="checkbox" checked={form.location_verified} onChange={(e) => setForm({...form, location_verified: e.target.checked})}/><span><strong>Tasdiqlangan lokatsiya</strong><small>Koordinata tekshirilgan bo'lsa belgilang</small></span></label><div className="modal-actions"><button type="button" className="btn ghost" onClick={() => setOpen(false)}>Bekor qilish</button><button className="btn primary" disabled={save.isPending}><Check/> {save.isPending ? 'Saqlanmoqda…' : 'Saqlash'}</button></div></form><div className="map-editor-side"><div><strong>Xaritadan belgilang</strong><small>Xaritani bosing yoki markerni suring</small></div><LocationPicker latitude={form.latitude} longitude={form.longitude} onChange={(latitude, longitude) => setForm((current) => ({...current, latitude, longitude}))}/></div></div></div></div>}
    <Toast toast={toast} onClose={() => setToast(null)}/>
  </AdminLayout>
}
