import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Database, KeyRound, RefreshCw, Route, Save, Server, ShieldCheck } from 'lucide-react'
import { api, ApiError } from '../api'
import Toast, { ToastState } from '../Toast'
import AdminLayout from '../AdminLayout'

export default function SettingsPage() {
  const client = useQueryClient()
  const [toast, setToast] = useState<ToastState | null>(null)
  const [router, setRouter] = useState('osrm')
  const [animationLimit, setAnimationLimit] = useState(100)
  const save = useMutation({ mutationFn: () => api('/settings/ui', { method: 'PUT', body: JSON.stringify({ routing_provider: router, animation_corridor_limit: animationLimit }) }), onSuccess: () => setToast({ type: 'success', message: 'Sozlamalar saqlandi' }), onError: (e) => setToast({ type: 'error', message: e instanceof ApiError ? e.message : 'Xato' }) })
  const reset = useMutation({ mutationFn: () => api<{ count: number }>('/declarations/mock/reset', { method: 'POST' }), onSuccess: (data) => { void client.invalidateQueries(); setToast({ type: 'success', message: `${data.count} ta mock deklaratsiya yaratildi` }) }, onError: (e) => setToast({ type: 'error', message: e instanceof ApiError ? e.message : 'Xato' }) })
  return <AdminLayout title="Tizim sozlamalari" subtitle="Routing, demo ma'lumotlar va xavfsizlik holati"><div className="settings-grid"><section className="panel settings-card"><div className="settings-title"><span><Route/></span><div><h2>Routing xizmati</h2><p>Yo'l geometriyasini hisoblash</p></div></div><label><span>Faol provider</span><select value={router} onChange={(e) => setRouter(e.target.value)}><option value="osrm">OSRM (demo)</option><option value="valhalla">Valhalla (adapter)</option><option value="graphhopper">GraphHopper (adapter)</option></select></label><label><span>Animatsiya limiti</span><input type="number" min={20} max={250} value={animationLimit} onChange={(e) => setAnimationLimit(Number(e.target.value))}/><small>Shu miqdordan ko'p corridor bo'lsa animatsiya soddalashadi.</small></label><button className="btn primary" onClick={() => save.mutate()}><Save/> Saqlash</button></section><section className="panel settings-card"><div className="settings-title"><span><Database/></span><div><h2>Demo ma'lumotlar</h2><p>Test deklaratsiyalarni yangilash</p></div></div><p className="settings-copy">Amal faqat <code>MOCK</code> manbali deklaratsiyalarni idempotent tarzda qayta yaratadi. ETRANZIT ma'lumotlariga tegmaydi.</p><button className="btn danger" disabled={reset.isPending} onClick={() => confirm('Mock deklaratsiyalar qayta yaratilsinmi?') && reset.mutate()}><RefreshCw/> {reset.isPending ? 'Yangilanmoqda…' : 'Mock ma’lumotni yangilash'}</button></section><section className="panel settings-card"><div className="settings-title"><span><ShieldCheck/></span><div><h2>Xavfsizlik</h2><p>Production nazorat ro'yxati</p></div></div><ul className="security-list"><li><KeyRound/><span><strong>HttpOnly sessiya cookie</strong><small>Token frontend storage'ga yozilmaydi</small></span><b>Faol</b></li><li><ShieldCheck/><span><strong>CSRF himoyasi</strong><small>O'zgartiruvchi so'rovlar uchun</small></span><b>Faol</b></li><li><Server/><span><strong>CORS allowlist</strong><small>Faqat ruxsat etilgan domenlar</small></span><b>ENV</b></li></ul></section></div><Toast toast={toast} onClose={() => setToast(null)}/></AdminLayout>
}
